# Generated by Django 4.1.7 on 2023-04-26 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_topic_topic_name_webpage_accessrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(validators=[django.core.validators.RegexValidator(None)]),
        ),
    ]
